spring.application.name=pet_shop
spring.datasource.url=jdbc:postgresql://localhost:5432/happypaws
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

<<<<<<< HEAD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8082
=======
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

<<<<<<< HEAD
server.port=8081
>>>>>>> 4f85f111e138f8244a347cfaaf22ca8445405ff3
=======

server.port=8083
>>>>>>> 5a7f942a67ef9e1b27cb7ba35247549f351ab190

